# Commands to be performed when the player votes for a server.
commands:
  - money give %name% 12.5

# Commands to be performed when the player has voted for all servers.
all-commands:
  - tell %name% Thank you for voting for New Liberty. You have been rewarded! Remember to vote again tomorrow!
  - tell %name% You now regain health when you kill another player and break blocks faster for the next 24 hours.
  - crent vote %name% 86400

# Sources of votes
services:
  PlanetMinecraft.com:
    name: Planet Minecraft
    link: http://www.planetminecraft.com/server/newliberty/
  MinecraftServers:
    name: MinecraftServers.net
    link: http://minecraftservers.net/server/59199/vote/
  Minestatus:
    name: Minestatus
    link: https://minestatus.net/78968/vote
  MinecraftServers.org:
    name: MinecraftServers.org
    link: http://minecraftservers.org/vote/67824
