# Commands to be performed when the player votes for a server.
commands:
  - money give %name% 12.5

# Commands to be performed when the player has voted for all servers.
all-commands:
  - tell %name% Thank you for voting for New Liberty. You have been rewarded! Remember to vote again tomorrow!
  - tell %name% You now regain health when you kill another player and break blocks faster for the next 24 hours.
  - crent vote %name% 86400

# Number of votes needed to use /vhome
votes-home: 3

# Sources of votes
services:
  a:
    id: PlanetMinecraft.com
    name: Planet Minecraft
  b:
    id: minecraftservers
    name: MinecraftServers.net
  c:
    id: Minestatus
    name: Minestatus
  d:
    id: MinecraftServers.org
    name: MinecraftServers.org
