name: EnderChestProtect
main: net.new_liberty.enderchestprotect.EnderChestProtect
version: 2.0.0
author: AlbireoX

commands:
  enderchest:
    desciption: Main ECP command
    usage: /enderchest <args>
