name: ${project.name}
description: ${project.description}
version: ${project.version}-b${buildNumber}
author: ${author}
website: ${project.url}

main: ${mainClass}
depend: [EasyDB, Votifier]

commands:
  vote:
    description: Shows a message detailing how to vote for the server.
    usage: /vote
  vhome:
    description: Teleports you to your vote home.
    usage: /vhome
  vsethome:
    description: Sets your vote home.
    usage: /vote

permissions:
  votesuite.admin:
    description: Allows full use of the plugin.
