name: EnderChestProtect
main: net.newliberty.enderchestprotect.EnderChestProtect
version: 2.0
author: AlbireoX

commands:
  enderchest:
    desciption: Main ECP command
    usage: /enderchest <args>
