name: ${project.name}
description: ${project.description}
version: ${project.version}-b${buildNumber}
author: ${author}
website: ${project.url}

main: ${mainClass}

permissions:
    noenderpearls.bypass:
        description: Allows bypassing of Ender Pearl restrictions.

