name: ${project.name}
description: ${project.description}
version: ${project.version}-b${buildNumber}
author: ${author}
website: ${project.url}

main: ${mainClass}
softdepend: [EasyDB]

commands:
  vote:
    description: Shows a message detailing how to vote for the server.
    usage: /vote

permissions:
  votesuite.admin:
    description: Allows full use of the plugin.
