name: ${project.name}
description: ${project.description}
version: ${describe}-b${buildNumber}
author: ${author}
website: ${project.url}

main: ${mainClass}
depend: [WorldGuard]
softdepend: [CombatTag, EasyDB, Votifier]

permissions:
  itemconomy.console:
    description: Allows use of the sign related commands.
  noenderpearls.bypass:
    description: Allows bypassing of Ender Pearl restrictions.
  chatcolorcommands.setcolors:
    description: Allows setting your prefix colors.
  chatcolorcommands.setchatcolor:
    description: Allows setting your chat color.
  chatcolorcommands.ranks.guardian:
    description: The Guardian rank on New Liberty.
    children:
      - chatcolorcommands.setcolors
  chatcolorcommands.ranks.champion:
    description: The Champion rank on New Liberty.
    children:
      - chatcolorcommands.setcolors
      - chatcolorcommands.setchatcolor
  specialeggs.segive:
    description: Gives an egg to the user or a target.
  stafflist.admin:
    description: Admin permission
  stafflist.mod:
    description: Mod permission
  stafflist.helper:
    description: Helper permission
  ecp.admin:
    description: Allows using other players' chests.

commands:
  list:
    description: Lists the online player count.
    usage: /list
  segive:
    description: Gives an egg to the user or a target.
    usage: /segive <egg> [amt] [target]
  setcolors:
    description: Allows setting your prefix colors.
    usage: /setcolors <colors>
  setchatcolor:
    description: Allows setting your chat color.
    usage: /setchatcolor <color>
  versionreport:
    description: Creates a version report which will be saved to a given file.
    usage: /versionreport <name>
  icbalance:
    description: Check someone''s balance
    usage: /icbalance <player>
  icsignbalance:
    description: Check yo balance
    usage: /icsignbalance <player>
  icsignbuy:
    description: Buy stuff
    usage: /icsignbuy <player> <price> <cmd>
  icsigndeposit:
    description: Deposit emeralds
    usage: /icsigndeposit <player> <amt>
  icsignwithdraw:
    description: Withdraw emeralds
    usage: /icsignwithdraw <player> <amt>
  ecclear:
    description: Clears Ender Chests.
    usage: /ecclear [player]
  ecconfirm:
    description: Confirms if you want to clear Ender Chests.
    usage: /ecconfirm
  eclist:
    description: Lists Ender Chests.
    usage: /eclist [player]
  ecview:
    description: Views an Ender Chest.
    usage: /ecview <chest id>
  vote:
    description: Shows a message detailing how to vote for the server.
    usage: /vote
  vhome:
    description: Teleports you to your vote home.
    usage: /vhome
  vsethome:
    description: Sets your vote home.
    usage: /vote
