name: ${project.name}
description: ${project.description}
version: ${project.version}-${build-commit-abbrev}-b${buildNumber}
author: ${author}
website: ${project.url}

main: ${mainClass}
depend: [WorldGuard, Vault]
softdepend: [CombatTag, Votifier]

commands:
  list:
    description: Lists the online player count.
    usage: /list
  segive:
    description: Gives an egg to the user or a target.
    usage: /segive <egg> [amt] [target]
  setcolors:
    description: Allows setting your prefix colors.
    usage: /setcolors <colors>
  setchatcolor:
    description: Allows setting your chat color.
    usage: /setchatcolor <color>
  versionreport:
    description: Creates a version report which will be saved to a given file.
    usage: /versionreport <name>
  icbalance:
    description: Check someone''s balance
    usage: /icbalance <player>
  icgrant:
    description: Grant someone emeralds
    usage: /icgrant <player> <amt>
  icsignbalance:
    description: Check yo balance
    usage: /icsignbalance <player>
  icsignbuy:
    description: Buy stuff
    usage: /icsignbuy <player> <price> <cmd>
  icsigndeposit:
    description: Deposit emeralds
    usage: /icsigndeposit <player> <amt>
  icsignwithdraw:
    description: Withdraw emeralds
    usage: /icsignwithdraw <player> <amt>
  icexchangesign:
    description: Creates an exchange sign
    usage: /icexchangesign <buy/sell> <amt>
  ecclear:
    description: Clears Ender Chests.
    usage: /ecclear [player]
  ecconfirm:
    description: Confirms if you want to clear Ender Chests.
    usage: /ecconfirm
  eclist:
    description: Lists Ender Chests.
    usage: /eclist [player]
  ecview:
    description: Views an Ender Chest.
    usage: /ecview <chest id>
  vote:
    description: Shows a message detailing how to vote for the server.
    usage: /vote
  vhome:
    description: Teleports you to your vote home.
    usage: /vhome
  vsethome:
    description: Sets your vote home.
    usage: /vote
  dbconfig:
    description: Configures the database
    usage: /dbconfig
  dbreload:
    description: Reloads the database
    usage: /dbreload
  horse:
    description: Manage your horses
    aliases: [h, khorse, keephorse]
