name: ${project.name}
description: ${project.description}
version: ${project.version}-b${buildNumber}
author: ${author}
website: ${project.url}

main: ${mainClass}

permissions:
  noenderpearls.bypass:
    description: Allows bypassing of Ender Pearl restrictions.
  chatcolorcommands.setcolors:
    description: Allows setting your prefix colors.
  chatcolorcommands.setchatcolor:
    description: Allows setting your chat color.
  chatcolorcommands.ranks.guardian:
    description: The Guardian rank on New Liberty.
    children:
      - chatcolorcommands.setcolors
  chatcolorcommands.ranks.champion:
    description: The Champion rank on New Liberty.
    children:
      - chatcolorcommands.setcolors
      - chatcolorcommands.setchatcolor

commands:
  list:
    description: Lists the online player count.
    usage: /list
  setcolors:
    description: Allows setting your prefix colors.
    usage: /setcolors <colors>
  setchatcolor:
    description: Allows setting your chat color.
    usage: /setchatcolor <color>
