name: HorseKeep
main: com.gmail.falistos.HorseKeep.HorseKeep
version: 0.1.3
depends: [Vault]
commands:
    horse:
        description: Manage your horses
        aliases: [h, khorse, keephorse]